version: '3.8'
services:
  postgresql:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders
    ports:
      - 127.0.0.1:5432:5432
